---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Sisco.
--- DateTime: 11/01/2026 19:28
---

group "00 Pardal Engine"

project "pardal-engine"
kind "StaticLib"
language "C++"
targetdir "%{BASE_DIR}libs/%{cfg.buildcfg}"

files {
    "%{BASE_DIR}packages/pardal-engine/**.h",
    "%{BASE_DIR}packages/pardal-engine/**.hpp",
    "%{BASE_DIR}packages/pardal-engine/**.inl",
    "%{BASE_DIR}packages/pardal-engine/**.cpp",
    "%{BASE_DIR}packages/pardal-engine/**.c"
}

includedirs {
    "%{BASE_DIR}packages/pardal-core/",
    "%{BASE_DIR}packages/pardal-render/",
    "%{BASE_DIR}packages/pardal-engine/",
}

links { "mimalloc", "pardal-core", "pardal-render" }

defines { "PDL_FEATURE_IMGUI" }

includeImGui()

configureCommonFlags()
configureCommonExternals()
setConfigurations()

filter {}

pardal.create_test_project("pardal-engine")
includedirs {
    "%{BASE_DIR}packages/pardal-render/",
    "%{BASE_DIR}packages/pardal-core/",
    "%{BASE_DIR}packages/pardal-engine/"
}

links { "pardal-core", "pardal-render", "pardal-engine", "imgui" }
