---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by franciscom.
--- DateTime: 19/01/2026 16:30
---

group "20 Pardal Apps"

project "pardal-engine-app"
kind "ConsoleApp"
links { "pardal-engine", "imgui" }
language "C++"
targetdir "%{BASE_DIR}bin/pardal-engine-app/%{cfg.buildcfg}"

files {
    "%{BASE_DIR}packages/pardal-engine-app/**.h",
    "%{BASE_DIR}packages/pardal-engine-app/**.hpp",
    "%{BASE_DIR}packages/pardal-engine-app/**.inl",
    "%{BASE_DIR}packages/pardal-engine-app/**.cpp",
    "%{BASE_DIR}packages/pardal-engine-app/**.c"
}

includedirs {
    "%{BASE_DIR}packages/pardal-core",
    "%{BASE_DIR}packages/pardal-render",
    "%{BASE_DIR}packages/pardal-engine",
    "%{BASE_DIR}packages/pardal-engine-app"
}

configureCommonFlags()
configureCommonExternals()

includeVulkan()
includeImGui()
includeSlang()
linkVulkan()
linkSlang()
setConfigurations()

links {"Tracy"}
filter {}
