---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by franciscom.
--- DateTime: 09/12/2025 12:28
---

group "10 Pardal Editor"

externalproject "Pardal"
filter {}
    kind "WindowedApp"
    language "C#"
    location "%{BASE_DIR}packages/pardal-editor/Pardal"
    uuid "FAE04EC0-301F-11D3-BF4B-00C04F79EFBC"
