name: Pardal CI

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]
      
jobs:
  generate-premake:
    name: Generate premake
    runs-on: windows-latest
    steps:
      - shell: cmd
      - uses: actions/checkout@master
      - run: cmd.exe /c 'generate_pardal.bat'
      
  build:
    name: Build Pardal
    runs-on: windows-latest
    needs: generate-premake
    steps:
      - uses: seanmiddleditch/gha-setup-vsdevenv@master
      - run: MSBuild.exe projects/pardal.sln /property:Configuration=Release

  test:
    name: Test pardal-core
    runs-on: windows-latest
    needs: build
    steps:
    - run: .\bin\pardal-core-tests\Release\pardal-core-tests.exe
      

